### ISSUE TITLE
jshint error - cannot read src of undefined

### ISSUE THREAD

**Issue by netpoetica** [jsoverson/grunt-contrib-jasmine-example#2]
Curious if you might know why the default task is giving me this error? 

``` javascript
Warning: Cannot read property 'src' of undefined Use --force to continue.
```

I'm able to get the jasmine test to work, but it doesn't like jshint. Not sure what 'src' it's looking for? Possibly the meta.src but that is most definitely defined.

Bringing this up as an issue because I'm thinking that maybe this repo might need to be updated to bring in some new versions of dependencies.

Thanks! 
-k

**Comment by netpoetica** [comment]
Was able to solve by following these instructions from https://github.com/gruntjs/grunt-contrib-jasmine/issues/17

Delete node_modules, run npm cache clean and re-run npm install to test.

Also, I added jshint to dependencies - not sure exactly which one was the solve, but both are probably good practice.

**Comment by netpoetica** [comment]
VERIFIED: you do not need to add jshint to dependancies, you simply need to clean the npm cache and reinstall

**Comment by jsoverson** [comment]
I do need to update the dependencies anyway to be up to date with the latest grunt rc/ 0.4.0 final and will do that today.
